/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author USER
 */
public class Registro extends javax.swing.JInternalFrame {
private javax.swing.JDesktopPane PanelPrincipal;
    /**
     * Creates new form Registro1
     */
    public Registro() {
        try {
            // Establecer el aspecto visual de JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            //com.jtattoo.plaf.aluminium.AluminiumLookAndFeel
            //com.jtattoo.plaf.noire.NoireLookAndFeel
            //com.jtattoo.plaf.aero.AeroLookAndFeel
            //com.jtattoo.plaf.acryl.AcrylLookAndFeel
            //com.jtattoo.plaf.mcwin.McWinLookAndFeel
            // TextureLookAndFeel
            //com.jtattoo.plaf.bernstein.BernsteinLookAndFeel
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(164, 177, 175));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 186, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 186, -1));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 186, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 230, 260));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/WhatsApp Image 2024-04-25 at 11.34.47 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
   String nombre = txtNombre.getText().trim();
    String usuario = txtUsuario.getText().trim();
    String contraseña = new String(txtContraseña.getPassword());

    // Validar que el nombre no contenga números
    if (!nombre.matches("[a-zA-Z\\s]+")) {
        JOptionPane.showMessageDialog(this, "El nombre no debe contener números.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar el formato del correo electrónico
    if (!usuario.matches("\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b")) {
        JOptionPane.showMessageDialog(this, "El usuario debe ser un correo electrónico válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verificar si el usuario ya está registrado
    if (usuarioRegistrado(usuario)) {
        JOptionPane.showMessageDialog(this, "El usuario ya está registrado.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Registrar los datos
    try {
        FileWriter writer = new FileWriter("datos.txt", true);
        writer.write("Nombre: " + nombre + "\n");
        writer.write("Usuario: " + usuario + "\n");
        writer.write("Clave: " + contraseña + "\n\n");
        writer.close();
        JOptionPane.showMessageDialog(this, "Registro exitoso.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al registrar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    limpiarCampos();
}
   
        private boolean usuarioRegistrado(String usuario) {
            try {
                File file = new File("datos.txt");
                Scanner scanner = new Scanner(file);
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    if (line.startsWith("Usuario: " + usuario)) {
                        scanner.close();
                        return true;
                    }
                }
                scanner.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
            return false;
            
    }//GEN-LAST:event_btnRegistrarActionPerformed
private void limpiarCampos(){
        txtNombre.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
